remote_theme: pages-themes/cayman@v0.2.0

title: "Розробка веб-застосунку 'Генератор сертифікатів'"

description: "Дипломна робота Анурєва К.С."

# Розробка веб-застосунку "Генератор сертифікатів"
Кваліфікаційна робота на підтвердження ступеня фахового молодшого бакалавра ([ВСП «ППФК НТУ «ХПІ»](http://polytechnic.poltava.ua)). 

Керівник роботи – Бабич Олена Володимирівна.

## Завдання до дипломної роботи
Розроблений програмний продукт має являти собою веб-застосунок для генерації, експорту та друку сертифікатів про проходження тренінгів, участь у вебінарах та заходах тощо. Слід подбати про привабливий й адаптивний інтерфейс користувача, передбачити вибір шаблону для створення сертифікату, можливість вводу (або вибору) необхідних даних, автоматичну генерацію унікального номеру сертифікату та збереження запису про нього у базі даних, розмежування прав доступу. Готовий продукт має бути опублікований в Мережі.

## Використані технології

- HTML5
- CSS
- JavaScript
- Vue.js
- Node.js

## Опублікований продукт
